analyzer:
  errors:
    avoid_dynamic_calls: ignore
    avoid_positional_boolean_parameters: ignore
    cascade_invocations: ignore
    depend_on_referenced_packages: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_untyped_parameter: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
